version: "3.8"

services:
  user:
    container_name: link
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
  mongodb:
    container_name: link-mongodb
    hostname: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_REPLICAS: mongo:27017
    ports:
      - "27017:27017"

networks:
  testnet:
    external: true

volumes:
  mongo_data: